export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const SAVE_USER = 'SAVE_USER';
export const EDIT_USER = 'EDIT_USER';
export const REMOVE_USER = 'REMOVE_USER'

export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCESS'

export const LOGIN_USER = 'REGISTER_USER'
export const LOGIN_USER_FAIL = 'REGISTER_USER_FAIL'
export const LOGIN_USER_SUCESS = 'REGISTER_USER_SUCESS'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
export const UPDATE_USER_SUCESS = 'UPDATE_USER_SUCESS'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const CREATE_PRODUCT_SUCCES = 'CREATE_PRODUCT_SUCCES'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const SET_EDIT_PRODUCT = 'SET_EDIT_PRODUCT';
